<?php


function caritas_config_block_info() {
    $block['user'] = array(
      'info' => t('le bloc du user'),
    );
    $block['bienvenue'] = array(
      'info' => t('le bloc message de leveque'),
    );
    $block['date'] = array(
      'info' => t('La date du jour'),
    );
    return $block;
  }


/**
     * Implements hook_block_view().
     */


function caritas_config_block_view($delta = ''){
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'user':
       $block['subject'] = caritas_config_user_subject();
       $block['content'] = caritas_config_block_content($delta);
       break;
    case 'bienvenue':
      $block['subject'] = '<none>';
      $block['content'] = caritas_config_block_content($delta);
      break;
    case 'date':
      $block['subject'] = '<none>';
      $block['content'] = caritas_config_block_content($delta);
      break;
}
  return $block;
}


function caritas_config_block_content ($swicth_block) {
  switch ($swicth_block) {
    case 'user':
      if(user_is_logged_in()) {
         global $user;
           $items = array();
             $name = $user->name;
           $items[] = l(t('Editer votre profile'), 'user', array('attributes' => array('title' => t('caritas_configifier votre profil'))));
                $items[] = l(t('Deconnexion...'), 'user/logout', array('attributes' => array('title' => t('Deconnexion'))));
            $output = '<div class="msg">' . t('BIENVENUE') . '</div>';
            $output .= theme('item_list', array('items' => $items));
        return $output;
      }
          break;
    case 'date':
        return date('l, F d, Y');
          break;
    case 'bienvenue':
      //$path =  'public://eveque.jpg'; 

 $variables = array(
      'path' => 'sites/all/themes/zeropoint/images/eveque.jpg', 
      'alt' => 'Test alt',
      'title' => 'Evêque',
      'attributes' => array('class' => 'some-img', 'id' => 'my-img'),
      );
  $outputy = theme('image', $variables);
  $outputx = '<div class="msg">' . t('Souhaits de bienvenue Mgr. Jean-Pierre BASSENE, Evêque de Kolda, Responsable de la commission de Pastorale Sociale au sein de la Conférence Episcopale, Abbé Ambroise Tine, Secrétaire Général de Caritas Sénégal et toute la CARITAS SENEGAL vous souhaitent la bienvenue sur le site et une bonne visite') . '</div>';
    // $outputy = theme('image_style', array( 'path' => $path, 'style_name' => 'bloc_photo'));
  $output = $outputy."".$outputx;
        return $output;
          break;
    } 
 }



function caritas_config_user_subject() {
if(user_is_logged_in()) {
    global $user;
    $name = $user->name;
    return t('Hello') . ' ' . $name;
  }
}

function caritas_config_image_default_styles() {
  $styles = array();
 
  $styles['caritas_config_new_style'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array('width' => 468, 'height' => '', 'upscale' => FALSE),
        'weight' => 0,
      ),
//                      array(
//        'name' => 'image_crop',
//        'data' => array('width' => 460, 'height' => 280, 'anchor' => 'center-bottom'),
//        'weight' => 1,
//      ),
    )
  );
  return $styles;
}



