<?php


/*
 * Disables bbcode and some other modules
 */



function caritas_config_update_7120() {
  module_disable(
    array(
      'bbcode',
      'bueditor', 
    ),
    TRUE
  );
  cache_clear_all();
  cache_clear_all();
}


/*
 * Disables caritas_partenaires 
 * and some other modules
 */


function caritas_config_update_7060() {
  module_enable(
    array(
      'caritas_partenaires',
      'caritas_zp', 
    ),
    TRUE
  );
}

